block.autoblock.render:
  listeners:
    - [BackBee\Event\Listener\AutoblockListener, onRender]

social.facebook.render:
  listeners:
    - [BackBee\Event\Listener\SocialListener, onRenderFacebook]

social.twitter.render:
  listeners:
    - [BackBee\Event\Listener\SocialListener, onRenderTwitter]

article.article.render:
  listeners:
    - [BackBee\Event\Listener\ArticleListener, onRender]

article.quote.render:
  listeners:
    - [BackBee\Event\Listener\QuoteListener, onRender]

home.slider.render:
    listeners:
        - [BackBee\Event\Listener\SliderListener, onRender]
